services:
  - type: web
    name: roleta-pro-frontend
    runtime: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_URL
        sync: false
    staticPublishPath: dist/public
    routes:
      - path: /
        destination: dist/public/index.html

  - type: web
    name: roleta-pro-backend
    runtime: node
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VITE_APP_URL
        sync: false
      - key: VITE_APP_TITLE
        value: Roleta Pro I.A.
      - key: VITE_APP_LOGO
        sync: false

